version: 2

# docs_dir: TP2/docs

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  version: "3.10"
  install:
    requirements: requirements.txt

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
