site_name: Libejovo

site_description: High level API for libejovo
site_author: Evan Voyles

# repo_url: https://github.com/ejovo13/libejovo

theme:
  # name: mkdocs
  features:
    - content.code.annotate
  name: readthedocs
  nav_style: dark
  hljs_style: monokai

nav:
  - Home: 'index.md'
  - Installation: 'Installation.md'
  - Tutorials: 'Tutorials.md'

# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences
