// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT TOUCH!!!

#pragma once
#define MAX_STEP_SIZE 100000

#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <assert.h>
#include "ejovo_rand.h"
#include <string.h>
#include <stdarg.h>
#include <complex.h>

#define MATRIX_SIZE(__MATRIX) __MATRIX->nrows * __MATRIX->ncols

#define FOREACH(MAT) for (size_t i = 0; i < MATRIX_SIZE(MAT); i++)
#define FORIJ(MAT, INIT_LOOP, INSIDE_LOOP, OUTSIDE_LOOP) \
    const size_t __m = MAT->nrows; \
    const size_t __n = MAT->ncols; \
        for (size_t i = 0; i < __m; i++) { \
        INIT_LOOP \
        for (size_t j = 0; j < __n; j++) {  \
            INSIDE_LOOP \
        } \
        OUTSIDE_LOOP\
    } \

